#!/usr/bin/env python
import os
import sys
import yaml
import argparse
from daybook import Daybook

DAYBOOK_CFG = os.path.join(os.getenv("HOME"), ".daybook.yml")

PYTHON_VERSION_ERROR = "Must be using Python 3.6+"

if sys.version_info[0] < 3:
    raise Exception(PYTHON_VERSION_ERROR)
else:
    if sys.version_info[1] < 6:
        raise Exception(PYTHON_VERSION_ERROR)


def get_project_config():
    parser = argparse.ArgumentParser()
    parser.add_argument("-n", "--name")
    parser.add_argument("-b", "--base_directory")

    args = parser.parse_args()
    if os.path.exists(DAYBOOK_CFG):
        with open(DAYBOOK_CFG) as fp:
            daybook_cfg = yaml.safe_load(fp.readlines())
    else:
        daybook_cfg = {}

    project_name = args.name
    project_dir = args.base_directory

    if not project_name:
        raise Exception("You must pass in a project name")

    if not project_dir:
        pre_existing_project_names = [c.get('name') for c in daybook_cfg]
        if project_name in pre_existing_project_names:
            base_projects = [c.get('directory') for c in daybook_cfg if c['name'] == project_name]
            if not base_projects:
                print("No such project found: {}".format(project_name))
                sys.exit(2)
            else:
                project = base_projects[1]
        else:
            raise Exception("You must pass in a base_directory argument")

    return (project_name, project_dir)


#
# MAIN
#

project_name, project_dir = get_project_config()
db = Daybook(project_name, project_dir)
